export const constants = {
  CI: "CI",
  NODE_ENV: "NODE_ENV",
  GTM_ID: "GTM_ID",
  SENTRY_DSN: "SENTRY_DSN",

  CONTENTFUL_SPACE_ID: "CONTENTFUL_SPACE_ID",
  CONTENTFUL_DELIVERY_ACCESS_TOKEN: "CONTENTFUL_DELIVERY_ACCESS_TOKEN",
}
